// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEkME0gwFiPgc-gFYIc2QJowE7KV7rsVw',
    appId: '1:856343140100:web:b3d0bab0f99b9a079d2251',
    messagingSenderId: '856343140100',
    projectId: 'settledin-a9928',
    authDomain: 'settledin-a9928.firebaseapp.com',
    storageBucket: 'settledin-a9928.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAonI8bv7jVNwipFLXWt3xV4ruqaqn_Bso',
    appId: '1:856343140100:android:c1cc62351116b38f9d2251',
    messagingSenderId: '856343140100',
    projectId: 'settledin-a9928',
    storageBucket: 'settledin-a9928.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5zolfOSeHh9zQiU6oXBtnBUjdx0WSc7s',
    appId: '1:856343140100:ios:e5b0de452c5973ab9d2251',
    messagingSenderId: '856343140100',
    projectId: 'settledin-a9928',
    storageBucket: 'settledin-a9928.appspot.com',
    androidClientId: '856343140100-2g4qhme3kffqphp4fssh0dhug4lofme8.apps.googleusercontent.com',
    iosClientId: '856343140100-82vjnp2qas9p64cdjlpevdigok35q6it.apps.googleusercontent.com',
    iosBundleId: 'com.example.settledinMerchant',
  );
}
